Sak 14 frontend refactoring img to svg
sakurassweets/sakurassweets-frontend pull request #62
Opened 2024-01-25 13:52 UTC by IrynaDidkivska

Implement:

-  Updated img to SVG:
    - added svg from React Icons Lib
-  Refactoring styles
-  Updated footer according to design

This is a:

- [x] 🍕 Feature
- [x] 🐛 Bug Fix
- [x] 🎨 Style
- [x] 🧑‍💻 Code Refactor

2024-01-25 14:08 UTC, sukui24 requested changes

2024-01-25 14:08 UTC, sukui24 commented on src/components/Footer/SocialList/SocialSVG.tsx
Move instagram, facebook and telegram links to constants.

2024-01-28 13:27 UTC, IrynaDidkivska commented on src/components/Footer/SocialList/SocialSVG.tsx
done

2024-01-28 13:29 UTC, IrynaDidkivska commented
- [x] added conts for socials and updated advantages list
- [x] added portal for Modal
- [x] updated modal form
- [x] refactoring img

2024-01-28 13:29 UTC, merged